server.port=8081
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
plugin-repo.packages-dir=plugin-packages
plugin-repo.db.path=plugin-repo.db






# 邮件配置
mail.host=smtp.qq.com
mail.port=587
mail.username=326794739@qq.com
mail.password=njlrzkylevllbgch
mail.from=326794739@qq.com