server.port=8081
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
plugin-repo.packages-dir=plugin-packages
plugin-repo.db.path=D:\\work\\hopaw-agent\\plugin-repo.db

# 邮件配置
mail.host=smtp.example.com
mail.port=587
mail.username=your-email@example.com
mail.password=your-password
mail.from=your-email@example.com